config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flat_path(@flat)
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :addres, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<h2>Edit a flat</h2>

<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "Update flat information", class: "btn btn-primary" %>
<% end %>

app/views/flats/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><%= link_to "Home", flats_path %></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
         <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"><%= link_to "Add a new flat", new_flat_path %></a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

<div class="d-flex flex-row bd-highlight mb-3">
  <% @flats.each do |flat| %>
  <div class="card d-flex justify-content-start" style="width: 18rem;">
    <img class="card-img-top" src="..." alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title"><%= link_to flat.name, flat_path(flat) %></h5>
      <p class="card-text"><%= flat.description %></p>
    </div>
    <div class="card-body">
      <a class="card-link"><%= link_to "More Info", flat_path(flat) %></a>
      <a class="card-link"><%= link_to "Edit", edit_flat_path(flat) %></a>
      <a class="card-link"><%= link_to "Delete",
            flat_path(flat),
            method: :delete,
            data: { confirm: "Are you sure?" }, style:"display:block" %></a>
    </div>
  </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<h2>Add a new flat</h2>

<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "Add a new flat", class: "btn btn-primary" %>
<% end %>

app/views/flats/show.html.erb
<h2><%= @flat.name %></h2>

<h3><%= @flat.address %></h3>

<p><%= @flat.description %></p>

<p><%= @flat.price_per_night %><br>
<p><%= @flat.number_of_guests %></p>

<%= link_to "Update flat info", edit_flat_path %>
<%= link_to "Back to Home", flats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>